<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ktsu.Essentials" Version="2.6.6" />
    <PackageVersion Include="ktsu.Essentials.FileSystemProviders.Native" Version="2.6.6" />
    <PackageVersion Include="ktsu.Essentials.PersistenceProviders.ConfigHome" Version="2.6.6" />
    <PackageVersion Include="ktsu.Essentials.SerializationProviders.Json" Version="2.6.6" />
    <PackageVersion Include="ktsu.TrayApp" Version="1.1.4" />
    <PackageVersion Include="Polyfill" Version="11.4.0" />
  </ItemGroup>
</Project>
